# Generated by Django 5.2.4 on 2025-07-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedpdf',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='chat_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
